edition = "2018"

reorder_modules = true
reorder_imports = true
reorder_impl_items = true
merge_imports = true

wrap_comments = false
comment_width = 80

struct_field_align_threshold = 30
struct_lit_single_line = false

combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
spaces_around_ranges = true
trailing_comma = "Always"

match_block_trailing_comma = true
force_multiline_blocks = true

report_todo = "Never"
report_fixme = "Never"